name: check-on-push

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v**'
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        java-version: ['17', '18']

    uses: ./.github/workflows/check.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      java-version: ${{ matrix.java-version }}
